# Generated by Django 4.2.27 on 2025-12-29 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="学校名称")),
                ("province", models.CharField(max_length=50, verbose_name="省份")),
                ("city", models.CharField(max_length=50, verbose_name="城市")),
                (
                    "district",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="区县"
                    ),
                ),
                (
                    "school_type",
                    models.CharField(
                        choices=[
                            ("junior", "初中"),
                            ("senior", "高中"),
                            ("combined", "完全中学"),
                        ],
                        default="senior",
                        max_length=20,
                        verbose_name="学校类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_schools",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "学校",
                "verbose_name_plural": "学校",
                "db_table": "schools",
                "indexes": [
                    models.Index(fields=["name"], name="schools_name_2838ce_idx"),
                    models.Index(
                        fields=["province", "city"], name="schools_provinc_d90a8d_idx"
                    ),
                ],
                "unique_together": {("name", "province", "city")},
            },
        ),
    ]
