# Generated by Django 4.2.27 on 2025-12-29 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "real_name",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="真实姓名"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/%Y/%m/",
                        verbose_name="头像",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, default="", max_length=500, verbose_name="个人简介"
                    ),
                ),
                (
                    "enrollment_year",
                    models.IntegerField(blank=True, null=True, verbose_name="入学年份"),
                ),
                (
                    "graduation_year",
                    models.IntegerField(blank=True, null=True, verbose_name="毕业年份"),
                ),
                (
                    "class_name",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="班级"
                    ),
                ),
                (
                    "is_profile_complete",
                    models.BooleanField(default=False, verbose_name="是否已完善资料"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alumni",
                        to="schools.school",
                        verbose_name="学校",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户资料",
                "verbose_name_plural": "用户资料",
                "db_table": "user_profiles",
            },
        ),
    ]
