# Generated by Django 4.2.27 on 2026-01-05 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_message_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后消息时间"
                    ),
                ),
                (
                    "user1_unread_count",
                    models.PositiveIntegerField(default=0, verbose_name="用户1未读数"),
                ),
                (
                    "user2_unread_count",
                    models.PositiveIntegerField(default=0, verbose_name="用户2未读数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "会话",
                "verbose_name_plural": "会话",
                "db_table": "conversations",
                "ordering": ["-last_message_time"],
            },
        ),
        migrations.CreateModel(
            name="PrivateMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=1000, verbose_name="消息内容")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="是否已读"),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="已读时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="campus_messages.conversation",
                        verbose_name="会话",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="接收者",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发送者",
                    ),
                ),
            ],
            options={
                "verbose_name": "私信",
                "verbose_name_plural": "私信",
                "db_table": "private_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="conversation",
            name="last_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="campus_messages.privatemessage",
                verbose_name="最后一条消息",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="user1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations_as_user1",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户1",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="user2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations_as_user2",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户2",
            ),
        ),
        migrations.AddIndex(
            model_name="privatemessage",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="private_mes_convers_895198_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="privatemessage",
            index=models.Index(
                fields=["receiver", "is_read"], name="private_mes_receive_cdf353_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conversation",
            unique_together={("user1", "user2")},
        ),
    ]
