# Generated by Django 4.2.27 on 2026-01-05 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("circles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlbumPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="albums/%Y/%m/", verbose_name="图片"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", max_length=500, verbose_name="照片备注"
                    ),
                ),
                (
                    "taken_at",
                    models.DateField(blank=True, null=True, verbose_name="拍摄时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="album_photos",
                        to="circles.circle",
                        verbose_name="所属圈子",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_photos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传者",
                    ),
                ),
            ],
            options={
                "verbose_name": "相册照片",
                "verbose_name_plural": "相册照片",
                "db_table": "album_photos",
                "ordering": ["-created_at"],
            },
        ),
    ]
