# Generated by Django 4.2.27 on 2026-01-01 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("circles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=5000, verbose_name="内容")),
                (
                    "images",
                    models.JSONField(blank=True, default=list, verbose_name="图片"),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="标签"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "正常"),
                            ("deleted", "已删除"),
                            ("violation", "违规删除"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("is_pinned", models.BooleanField(default=False, verbose_name="置顶")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="精华"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览量"),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(default=0, verbose_name="点赞数"),
                ),
                (
                    "comment_count",
                    models.PositiveIntegerField(default=0, verbose_name="评论数"),
                ),
                (
                    "hot_score",
                    models.PositiveIntegerField(default=0, verbose_name="热度分数"),
                ),
                (
                    "last_reply_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后回复时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="circles.circle",
                        verbose_name="所属圈子",
                    ),
                ),
            ],
            options={
                "verbose_name": "帖子",
                "verbose_name_plural": "帖子",
                "db_table": "posts",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
    ]
