# Generated by Django 4.2.27 on 2026-01-01 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Circle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "circle_type",
                    models.CharField(
                        choices=[
                            ("school", "校级圈"),
                            ("grade", "年级圈"),
                            ("class", "班级圈"),
                        ],
                        max_length=20,
                        verbose_name="圈子类型",
                    ),
                ),
                (
                    "grade_year",
                    models.IntegerField(blank=True, null=True, verbose_name="入学年份"),
                ),
                (
                    "class_name",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="班级名称"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="圈子名称")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", max_length=500, verbose_name="圈子简介"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_circles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_circles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="圈主",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circles",
                        to="schools.school",
                        verbose_name="学校",
                    ),
                ),
            ],
            options={
                "verbose_name": "话题圈",
                "verbose_name_plural": "话题圈",
                "db_table": "circles",
                "unique_together": {
                    ("school", "circle_type", "grade_year", "class_name")
                },
            },
        ),
        migrations.CreateModel(
            name="CircleMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("member", "普通成员"), ("admin", "管理员")],
                        default="member",
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="circles.circle",
                        verbose_name="圈子",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circle_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "圈子成员",
                "verbose_name_plural": "圈子成员",
                "db_table": "circle_members",
                "unique_together": {("circle", "user")},
            },
        ),
    ]
